<x-app-layout>
    <x-slot name="header">
        <div class="d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3"><div><p class="cricket-kicker mb-2">Captain reports</p><h1 class="display-6 fw-bold mb-2">{{ $report['tournament']->name }}</h1><p class="text-secondary mb-0">Your team’s squad, draft history, tournament summary, and timer status.</p></div><a href="{{ route('captain.dashboard') }}" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Captain dashboard</a></div>
    </x-slot>
    <div class="container pb-5">
        <div class="cricket-pitch-panel p-4 p-lg-5 mb-4"><p class="cricket-kicker mb-2">Team report</p><h2 class="h2 fw-bold mb-2">{{ $report['captain_team'] ?: 'Assigned team' }}</h2><p class="text-white-50 mb-0">Captain-only view. Internal registrations, audit IPs, and other teams’ private actions are not included.</p></div>
        <div class="row g-3 mb-4">@foreach ([['selected_players','Your selected players'],['total_picks','Draft picks'],['completed_picks','Completed picks'],['extended_seconds','Extended seconds']] as [$key,$label])<div class="col-6 col-lg-3"><div class="cricket-surface p-3"><div class="small text-secondary">{{ $label }}</div><div class="cricket-stat-value mt-2">{{ $report['summary'][$key] ?? $report['timer'][$key] ?? 0 }}</div></div></div>@endforeach</div>
        <div class="cricket-surface p-4 p-lg-5 mb-4"><div class="d-flex align-items-center justify-content-between gap-3 mb-4"><div><p class="cricket-kicker mb-2">Download center</p><h2 class="h3 fw-bold mb-1">Captain reports</h2><p class="text-secondary mb-0">Download the reports relevant to your team.</p></div><i class="fa-solid fa-file-pdf text-danger fs-2"></i></div><div class="row g-3">@foreach($reportTypes as $type => $label)<div class="col-md-6 col-lg-3"><div class="cricket-surface-soft p-3 h-100 d-flex flex-column"><div class="fw-bold">{{ $label }}</div><div class="small text-secondary mb-3">PDF download</div><a href="{{ route('captain.reports.pdf', [$report['tournament'], $type]) }}" class="btn btn-outline-danger btn-sm mt-auto"><i class="fa-solid fa-download me-1"></i>Download PDF</a></div></div>@endforeach</div></div>
        <div class="row g-4"><div class="col-xl-6"><div class="cricket-surface p-4 h-100"><h2 class="h4 fw-bold mb-3">Your team squad</h2><div class="vstack gap-2">@forelse($report['team_squads']->first()['players'] ?? [] as $player)<div class="cricket-surface-soft p-3 d-flex justify-content-between"><span class="fw-bold">{{ $player['player'] }}</span><span class="small text-secondary">{{ $player['playing_role'] ?: 'Unassigned' }}</span></div>@empty<div class="text-secondary">No player has been selected for your team yet.</div>@endforelse</div></div></div><div class="col-xl-6"><div class="cricket-surface p-4 h-100"><h2 class="h4 fw-bold mb-3">Your pick history</h2><div class="vstack gap-2">@forelse($report['history'] as $pick)<div class="cricket-surface-soft p-3 d-flex justify-content-between"><span><strong>#{{ $pick['pick_number'] }}</strong> · {{ $pick['player'] ?: '—' }}</span><span class="small text-secondary">{{ ucfirst($pick['status']) }}</span></div>@empty<div class="text-secondary">No picks recorded for your team yet.</div>@endforelse</div></div></div></div>
    </div>
</x-app-layout>
