<x-app-layout>
    <x-slot name="header"><div><p class="cricket-kicker mb-2">Captain workspace</p><h1 class="display-6 fw-bold mb-2">Your draft rooms.</h1><p class="text-secondary mb-0">See your assigned teams, watch the tournament state, and be ready when the clock starts.</p></div></x-slot>

    <div class="container pb-5">
        <div class="cricket-pitch-panel p-4 p-lg-5 mb-4"><div class="row align-items-center g-4"><div class="col-lg-8"><p class="cricket-kicker mb-2">Captain briefing</p><h2 class="h2 fw-bold mb-2">Your call is the only call that matters on your turn.</h2><p class="text-white-50 mb-0">The server checks your team assignment, the active pick, player approval, and the timer before accepting every selection.</p></div><div class="col-lg-4 text-lg-end"><i class="fa-solid fa-shield-halved" style="font-size:5rem; color:var(--cricket-lime); opacity:.85;"></i></div></div></div>
        <div class="d-flex align-items-center justify-content-between gap-3 mb-4"><div><p class="cricket-kicker mb-2">Assignments</p><h2 class="h3 fw-bold mb-1">Your tournaments</h2><p class="text-secondary mb-0">Only active assignments appear here.</p></div><span class="badge text-bg-light">{{ $tournaments->count() }} assigned</span></div>
        @if ($tournaments->isEmpty())
            <div class="cricket-surface p-5 text-center"><span class="cricket-brand-mark mb-4"><i class="fa-solid fa-hourglass-half"></i></span><h3 class="h4 fw-bold">No captain assignment yet</h3><p class="text-secondary mb-0">An administrator will assign you to a team before draft day.</p></div>
        @else
            <div class="row g-4">
                @foreach ($tournaments as $tournament)
                    @php
                        $teamNames = $assignments->filter(fn ($assignment) => $assignment->team?->tournament_id === $tournament->id)->pluck('team.name')->filter()->join(', ');
                        $captainReport = $reports[$tournament->id] ?? null;
                    @endphp
                    <div class="col-lg-6"><div class="cricket-surface p-4 p-lg-5 h-100 d-flex flex-column"><div class="d-flex align-items-start justify-content-between gap-3 mb-4"><span class="cricket-brand-mark"><i class="fa-solid fa-users"></i></span><span class="badge text-bg-{{ $tournament->status === 'live' ? 'success' : 'light' }}">{{ ucfirst($tournament->status) }}</span></div><div class="small text-secondary mb-1">Assigned team{{ $teamNames ? '' : 's' }}</div><h3 class="h3 fw-bold mb-2">{{ $teamNames ?: 'Team assignment' }}</h3><p class="text-secondary mb-4">{{ $tournament->name }}</p>@if($captainReport)<div class="cricket-surface-soft p-3 mb-4"><div class="d-flex align-items-center justify-content-between gap-2 mb-3"><div><div class="small text-secondary">Selected players</div><div class="fw-bold">{{ $captainReport['team_squads']->first()['selected_count'] ?? 0 }} selected</div></div><a href="{{ route('captain.reports.pdf', [$tournament, 'squads']) }}" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-download me-1"></i>Download team PDF</a></div><div class="vstack gap-2">@forelse(($captainReport['team_squads']->first()['players'] ?? []) as $player)<div class="bg-white rounded-3 p-2 d-flex align-items-center justify-content-between"><span class="fw-bold text-truncate">{{ $player['player'] }}</span><span class="small text-secondary ms-2">{{ $player['playing_role'] ?: 'Unassigned' }}</span></div>@empty<div class="small text-secondary">No player selected yet.</div>@endforelse</div></div>@endif<div class="cricket-surface-soft p-3 mb-4"><div class="d-flex justify-content-between small"><span class="text-secondary">Tournament state</span><strong>{{ ucfirst($tournament->status) }}</strong></div><div class="d-flex justify-content-between small mt-2"><span class="text-secondary">Draft room</span><strong>{{ $tournament->draft ? ucfirst($tournament->draft->status) : 'Not configured' }}</strong></div></div><div class="mt-auto">@if ($tournament->status === 'live' && $tournament->draft)<a href="{{ route('captain.draft.show', $tournament) }}" class="btn btn-success w-100"><i class="fa-solid fa-tower-broadcast me-2"></i>Open live draft room</a>@else<div class="small text-secondary"><i class="fa-solid fa-clock me-2 text-success"></i>Waiting for the administrator to start the live draft.</div>@endif</div></div></div>@endforeach</div>
        @endif
    </div>
</x-app-layout>
