<x-app-layout>
    <x-slot name="header">
        <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">Identity governance</p><h1 class="display-6 fw-bold mb-2">Users and roles</h1><p class="text-secondary mb-0">Review every platform identity, inspect activity, manage role boundaries, and revoke API access when required.</p></div><a href="{{ route('super-admin.dashboard') }}" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Control plane</a></div>
    </x-slot>
    <div class="container pb-5">
        <div class="row g-3 mb-4">
            @foreach(['super_admin' => 'Super Admins', 'admin' => 'Administrators', 'captain' => 'Captains', 'player' => 'Players'] as $role => $label)
                <div class="col-6 col-xl-3"><a href="{{ route('super-admin.users.index', ['role' => $role]) }}" class="cricket-surface p-4 h-100 text-decoration-none d-block"><div class="small text-secondary">{{ $label }}</div><div class="display-6 fw-bold text-dark">{{ $roleCounts[$role] ?? 0 }}</div><div class="small text-success mt-2">Filter this role <i class="fa-solid fa-arrow-right ms-1"></i></div></a></div>
            @endforeach
        </div>
        @if(session('status'))<div class="alert alert-success border-0 shadow-sm">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="alert alert-danger border-0 shadow-sm">{{ $errors->first() }}</div>@endif
        <div class="cricket-surface p-4 mb-4">
            <form method="GET" class="row g-2 align-items-end"><div class="col-lg-6"><label class="form-label small text-secondary">Search user</label><input type="search" name="search" value="{{ $search }}" class="form-control" placeholder="Name or email"></div><div class="col-lg-3"><label class="form-label small text-secondary">Role</label><select name="role" class="form-select"><option value="">All roles</option>@foreach(['super_admin' => 'Super Admin', 'admin' => 'Administrator', 'captain' => 'Captain', 'player' => 'Player'] as $role => $label)<option value="{{ $role }}" @selected($selectedRole === $role)>{{ $label }}</option>@endforeach</select></div><div class="col-lg-3 d-flex gap-2"><button class="btn btn-success flex-grow-1"><i class="fa-solid fa-filter me-2"></i>Apply filters</button><a href="{{ route('super-admin.users.index') }}" class="btn btn-light">Reset</a></div></form>
        </div>
        <div class="cricket-surface overflow-hidden"><div class="d-flex justify-content-between align-items-center gap-3 p-4 border-bottom"><div><p class="cricket-kicker mb-1">Directory</p><h2 class="h4 fw-bold mb-0">Platform identities</h2></div><span class="small text-secondary">{{ $users->total() }} total matches</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>User</th><th>Role</th><th>API sessions</th><th>Audit events</th><th>Joined</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($users as $user)<tr><td><div class="fw-semibold">{{ $user->name }}</div><div class="small text-secondary">{{ $user->email }}</div></td><td><span class="badge {{ $user->getRoleNames()->first() === 'super_admin' ? 'text-bg-dark' : 'text-bg-light' }}">{{ str_replace('_', ' ', ucfirst($user->getRoleNames()->first() ?: 'member')) }}</span></td><td>{{ $user->tokens_count }}</td><td>{{ $user->audit_logs_count }}</td><td class="text-secondary">{{ $user->created_at?->format('d M Y') }}</td><td class="text-end"><a href="{{ route('super-admin.users.show', $user) }}" class="btn btn-sm btn-outline-success">Inspect</a></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-secondary">No identities match the selected filters.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $users->links() }}</div>
    </div>
</x-app-layout>
