<x-app-layout>
    <x-slot name="header"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">Identity governance</p><h1 class="display-6 fw-bold mb-2">{{ $user->name }}</h1><p class="text-secondary mb-0">{{ $user->email }} · user #{{ $user->id }}</p></div><a href="{{ route('super-admin.users.index') }}" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Back to users</a></div></x-slot>
    <div class="container pb-5">
        @if(session('status'))<div class="alert alert-success border-0 shadow-sm">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="alert alert-danger border-0 shadow-sm">{{ $errors->first() }}</div>@endif
        <div class="row g-4 mb-4">
            <div class="col-xl-7"><div class="cricket-surface p-4 p-lg-5 h-100"><div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><p class="cricket-kicker mb-1">Identity profile</p><h2 class="h3 fw-bold mb-1">Account controls</h2><p class="text-secondary mb-0">Role changes are audited and the platform protects the last remaining Super Admin.</p></div><span class="badge text-bg-light">{{ $user->email_verified_at ? 'Verified email' : 'Unverified email' }}</span></div><div class="row g-3 mb-4"><div class="col-6 col-md-3"><div class="small text-secondary">API sessions</div><div class="h3 fw-bold mb-0">{{ $user->tokens_count }}</div></div><div class="col-6 col-md-3"><div class="small text-secondary">Audit events</div><div class="h3 fw-bold mb-0">{{ $user->audit_logs_count }}</div></div><div class="col-6 col-md-3"><div class="small text-secondary">Reviews</div><div class="h3 fw-bold mb-0">{{ $user->reviewed_tournament_players_count }}</div></div><div class="col-6 col-md-3"><div class="small text-secondary">Draft picks</div><div class="h3 fw-bold mb-0">{{ $user->selected_draft_picks_count }}</div></div></div><form method="POST" action="{{ route('super-admin.users.role.update', $user) }}" class="row g-2 align-items-end">@csrf<div class="col-md-8"><label class="form-label small text-secondary">Platform role</label><select class="form-select" name="role">@foreach(['super_admin' => 'Super Admin', 'admin' => 'Administrator', 'captain' => 'Captain', 'player' => 'Player'] as $role => $label)<option value="{{ $role }}" @selected($user->getRoleNames()->first() === $role)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><button class="btn btn-success w-100" onclick="return confirm('Apply this role change and write an audit event?')"><i class="fa-solid fa-shield-halved me-2"></i>Update role</button></div></form></div></div>
            <div class="col-xl-5"><div class="cricket-surface p-4 p-lg-5 h-100"><p class="cricket-kicker mb-1">Access containment</p><h2 class="h4 fw-bold mb-2">Revoke API sessions</h2><p class="text-secondary">Use this when a device is lost, credentials are rotated, or suspicious activity is detected. This does not delete the user.</p><form method="POST" action="{{ route('super-admin.users.sessions.revoke', $user) }}" class="mt-4">@csrf<button class="btn btn-outline-danger w-100" onclick="return confirm('Revoke every API session for this user?')"><i class="fa-solid fa-ban me-2"></i>Revoke {{ $user->tokens_count }} session(s)</button></form><dl class="row small mt-4 mb-0"><dt class="col-5 text-secondary">Created</dt><dd class="col-7">{{ $user->created_at?->format('d M Y H:i') }}</dd><dt class="col-5 text-secondary">Last updated</dt><dd class="col-7">{{ $user->updated_at?->format('d M Y H:i') }}</dd><dt class="col-5 text-secondary">Current role</dt><dd class="col-7 text-capitalize">{{ str_replace('_', ' ', $user->getRoleNames()->first() ?: 'member') }}</dd></dl></div></div>
        </div>
        <div class="row g-4"><div class="col-xl-6"><div class="cricket-surface overflow-hidden"><div class="p-4 border-bottom"><p class="cricket-kicker mb-1">Active and historic sessions</p><h2 class="h4 fw-bold mb-0">API session ledger</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Device</th><th>Last used</th><th>Expires</th></tr></thead><tbody>@forelse($sessions as $session)<tr><td><div class="fw-semibold">{{ $session->name }}</div><div class="small text-secondary">#{{ $session->id }}</div></td><td class="text-secondary">{{ $session->last_used_at?->format('d M Y H:i') ?: 'Never' }}</td><td class="text-secondary">{{ $session->expires_at?->format('d M Y H:i') ?: 'No expiry' }}</td></tr>@empty<tr><td colspan="3" class="text-center py-4 text-secondary">No API sessions found.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-xl-6"><div class="cricket-surface overflow-hidden"><div class="p-4 border-bottom"><p class="cricket-kicker mb-1">Security history</p><h2 class="h4 fw-bold mb-0">User audit events</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Action</th><th>Scope</th><th>Time</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr><td><span class="badge text-bg-light">{{ $log->action }}</span></td><td>{{ $log->tournament?->name ?: 'Platform' }}</td><td class="text-secondary">{{ $log->created_at?->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="3" class="text-center py-4 text-secondary">No user audit events found.</td></tr>@endforelse</tbody></table></div></div></div></div>
    </div>
</x-app-layout>
