<x-app-layout>
    <x-slot name="header"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">API governance</p><h1 class="display-6 fw-bold mb-2">API clients</h1><p class="text-secondary mb-0">Register, monitor, and contain web, mobile, and internal applications connected to the platform.</p></div><div class="d-flex gap-2"><a href="{{ route('super-admin.dashboard') }}" class="btn btn-light">Control plane</a><a href="{{ route('super-admin.api-clients.create') }}" class="btn btn-success"><i class="fa-solid fa-plus me-2"></i>Register client</a></div></div></x-slot>
    <div class="container pb-5">
        @if(session('status'))<div class="alert alert-success border-0 shadow-sm">{{ session('status') }}</div>@endif
        <div class="row g-3 mb-4"><div class="col-md-6"><a href="{{ route('super-admin.api-clients.index', ['status' => 'active']) }}" class="cricket-surface p-4 h-100 text-decoration-none d-block"><div class="small text-secondary">Active clients</div><div class="display-6 fw-bold text-success">{{ $activeCount }}</div><div class="small text-secondary">Allowed to create sessions</div></a></div><div class="col-md-6"><a href="{{ route('super-admin.api-clients.index', ['status' => 'disabled']) }}" class="cricket-surface p-4 h-100 text-decoration-none d-block"><div class="small text-secondary">Disabled clients</div><div class="display-6 fw-bold">{{ $disabledCount }}</div><div class="small text-secondary">Login requests rejected</div></a></div></div>
        <div class="cricket-surface p-4 mb-4"><form method="GET" class="row g-2 align-items-end"><div class="col-lg-8"><label class="form-label small text-secondary">Search client</label><input type="search" name="search" value="{{ $search }}" class="form-control" placeholder="Name, slug, or platform"></div><div class="col-lg-2"><label class="form-label small text-secondary">Status</label><select name="status" class="form-select"><option value="">All</option><option value="active" @selected($selectedStatus === 'active')>Active</option><option value="disabled" @selected($selectedStatus === 'disabled')>Disabled</option></select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-success flex-grow-1">Filter</button><a href="{{ route('super-admin.api-clients.index') }}" class="btn btn-light">Reset</a></div></form></div>
        <div class="cricket-surface overflow-hidden"><div class="d-flex justify-content-between align-items-center gap-3 p-4 border-bottom"><div><p class="cricket-kicker mb-1">Client registry</p><h2 class="h4 fw-bold mb-0">Registered applications</h2></div><span class="small text-secondary">{{ $clients->total() }} total matches</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Client</th><th>Platform</th><th>Version</th><th>Rate limit</th><th>Status</th><th>Last seen</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($clients as $client)<tr><td><strong>{{ $client->name }}</strong><div class="small text-secondary">{{ $client->slug }}</div><div class="small text-secondary">Created by {{ $client->creator?->name ?: 'System' }}</div></td><td>{{ ucfirst($client->platform) }}</td><td>{{ $client->version ?: '—' }}</td><td>{{ $client->rate_limit_per_minute }}/min</td><td><span class="badge {{ $client->is_active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $client->is_active ? 'Active' : 'Disabled' }}</span></td><td class="text-secondary">{{ $client->last_seen_at?->format('d M Y H:i') ?: 'Never' }}</td><td class="text-end"><form method="POST" action="{{ route('super-admin.api-clients.toggle', $client) }}" onsubmit="return confirm('{{ $client->is_active ? 'Disable' : 'Activate' }} this API client?')">@csrf<button class="btn btn-sm {{ $client->is_active ? 'btn-outline-danger' : 'btn-outline-success' }}" type="submit">{{ $client->is_active ? 'Disable' : 'Activate' }}</button></form></td></tr>@empty<tr><td colspan="7" class="text-center py-5 text-secondary">No API clients match the selected filters.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $clients->links() }}</div>
    </div>
</x-app-layout>
