<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">Platform reliability</p><h1 class="display-6 fw-bold mb-2">System health</h1><p class="text-secondary mb-0">Runtime checks for the application, database, API, storage, queue, scheduler, and production security posture.</p></div><div class="text-lg-end"><div class="small text-secondary">Last checked</div><div class="fw-semibold"><?php echo e($checkedAt?->format('d M Y H:i:s T')); ?></div></div></div> <?php $__env->endSlot(); ?>
    <div class="container pb-5">
        <div class="row g-3 mb-4"><?php $__currentLoopData = $checks; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $check): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-12 col-md-6 col-xl-4"><div class="cricket-surface p-4 h-100 border-start border-4 <?php echo e($check['status'] === 'healthy' ? 'border-success' : ($check['status'] === 'warning' ? 'border-warning' : 'border-danger')); ?>"><div class="d-flex justify-content-between align-items-start gap-3"><div><div class="small text-secondary"><?php echo e($check['label']); ?></div><div class="h4 fw-bold mb-1"><?php echo e($check['value']); ?></div></div><span class="badge <?php echo e($check['status'] === 'healthy' ? 'text-bg-success' : ($check['status'] === 'warning' ? 'text-bg-warning' : 'text-bg-danger')); ?>"><?php echo e(ucfirst($check['status'])); ?></span></div><p class="small text-secondary mb-0"><?php echo e($check['detail']); ?></p></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
        <div class="row g-4"><div class="col-xl-7"><div class="cricket-surface p-4 p-lg-5 h-100"><p class="cricket-kicker mb-1">Runtime profile</p><h2 class="h4 fw-bold mb-4">Environment details</h2><dl class="row mb-0"><dt class="col-sm-4 text-secondary">Application URL</dt><dd class="col-sm-8 text-break"><?php echo e($environment['app_url'] ?: 'Not configured'); ?></dd><dt class="col-sm-4 text-secondary">Environment</dt><dd class="col-sm-8"><?php echo e(app()->environment()); ?></dd><dt class="col-sm-4 text-secondary">PHP</dt><dd class="col-sm-8"><?php echo e($environment['php']); ?></dd><dt class="col-sm-4 text-secondary">Laravel</dt><dd class="col-sm-8"><?php echo e($environment['laravel']); ?></dd><dt class="col-sm-4 text-secondary">Timezone</dt><dd class="col-sm-8"><?php echo e($environment['timezone']); ?></dd><dt class="col-sm-4 text-secondary">Debug mode</dt><dd class="col-sm-8"><span class="badge <?php echo e($environment['debug'] ? 'text-bg-warning' : 'text-bg-success'); ?>"><?php echo e($environment['debug'] ? 'Enabled' : 'Disabled'); ?></span></dd><dt class="col-sm-4 text-secondary">Maintenance</dt><dd class="col-sm-8"><span class="badge <?php echo e($environment['maintenance'] ? 'text-bg-danger' : 'text-bg-success'); ?>"><?php echo e($environment['maintenance'] ? 'Enabled' : 'Off'); ?></span></dd></dl></div></div><div class="col-xl-5"><div class="cricket-surface p-4 p-lg-5 h-100"><p class="cricket-kicker mb-1">Production checklist</p><h2 class="h4 fw-bold mb-4">Recommended actions</h2><div class="vstack gap-3"><div class="d-flex gap-3"><i class="fa-solid fa-database text-success mt-1"></i><div><div class="fw-semibold">Database backup</div><div class="small text-secondary">Confirm scheduled MySQL backups before production tournaments.</div></div></div><div class="d-flex gap-3"><i class="fa-solid fa-clock text-warning mt-1"></i><div><div class="fw-semibold">Scheduler and workers</div><div class="small text-secondary">Configure cron and queue workers on the cPanel host.</div></div></div><div class="d-flex gap-3"><i class="fa-solid fa-lock text-success mt-1"></i><div><div class="fw-semibold">Secrets and debug</div><div class="small text-secondary">Keep `.env` outside downloads and set APP_DEBUG=false in production.</div></div></div><div class="d-flex gap-3"><i class="fa-solid fa-shield-halved text-success mt-1"></i><div><div class="fw-semibold">Session containment</div><div class="small text-secondary">Review active API sessions and revoke stale credentials regularly.</div></div></div></div></div></div></div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/super-admin/health.blade.php ENDPATH**/ ?>