<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">Platform operations</p><h1 class="display-6 fw-bold mb-2"><?php echo e($tournament->name); ?></h1><p class="text-secondary mb-0"><?php echo e($tournament->season_name ?: 'No season name'); ?> · <?php echo e($tournament->slug); ?></p></div><div class="d-flex gap-2"><a href="<?php echo e(route('super-admin.tournaments.index')); ?>" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Fleet</a><a href="<?php echo e(route('admin.tournaments.show', $tournament)); ?>" class="btn btn-success"><i class="fa-solid fa-arrow-up-right-from-square me-2"></i>Open admin workspace</a></div></div> <?php $__env->endSlot(); ?>
    <div class="container pb-5">
        <div class="d-flex flex-wrap align-items-center gap-2 mb-4"><span class="badge <?php echo e($tournament->status === 'live' ? 'text-bg-success' : 'text-bg-light'); ?>"><?php echo e(ucfirst($tournament->status)); ?></span><span class="badge text-bg-light"><?php echo e($tournament->is_public ? 'Public' : 'Private'); ?></span><span class="small text-secondary"><?php echo e($tournament->venue ?: $tournament->city ?: 'Location not set'); ?> · <?php echo e($tournament->timezone); ?></span></div>
        <div class="row g-3 mb-4"><?php $__currentLoopData = [['Teams', $tournament->teams_count], ['Players', $tournament->tournament_players_count], ['Fixtures', $tournament->fixtures_count], ['Matches', $tournament->matches_count], ['Audit events', $tournament->audit_logs_count]]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$label, $value]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-6 col-md"><div class="cricket-surface p-4 h-100"><div class="small text-secondary"><?php echo e($label); ?></div><div class="display-6 fw-bold"><?php echo e($value); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
        <div class="row g-4 mb-4"><div class="col-xl-5"><div class="cricket-surface p-4 p-lg-5 h-100"><p class="cricket-kicker mb-1">Tournament configuration</p><h2 class="h4 fw-bold mb-4">Operational profile</h2><dl class="row mb-0"><dt class="col-6 text-secondary">Season</dt><dd class="col-6"><?php echo e($tournament->season_name ?: '—'); ?></dd><dt class="col-6 text-secondary">Squad size</dt><dd class="col-6"><?php echo e($tournament->squad_size); ?></dd><dt class="col-6 text-secondary">Pick timer</dt><dd class="col-6"><?php echo e($tournament->default_pick_duration); ?> sec</dd><dt class="col-6 text-secondary">Starts</dt><dd class="col-6"><?php echo e($tournament->starts_on?->format('d M Y') ?: '—'); ?></dd><dt class="col-6 text-secondary">Ends</dt><dd class="col-6"><?php echo e($tournament->ends_on?->format('d M Y') ?: '—'); ?></dd><dt class="col-6 text-secondary">Registration</dt><dd class="col-6"><?php echo e($tournament->registrationIsOpen() ? 'Open now' : 'Closed now'); ?></dd></dl><div class="d-flex flex-wrap gap-2 mt-4"><a href="<?php echo e(route('admin.tournaments.teams.index', $tournament)); ?>" class="btn btn-sm btn-light">Teams</a><a href="<?php echo e(route('admin.tournaments.players.index', $tournament)); ?>" class="btn btn-sm btn-light">Players</a><a href="<?php echo e(route('admin.tournaments.fixtures.index', $tournament)); ?>" class="btn btn-sm btn-light">Fixtures</a><a href="<?php echo e(route('admin.tournaments.matches.index', $tournament)); ?>" class="btn btn-sm btn-light">Matches</a></div></div></div><div class="col-xl-7"><div class="cricket-surface p-4 p-lg-5 h-100"><div class="d-flex justify-content-between align-items-center mb-3"><div><p class="cricket-kicker mb-1">Teams and captains</p><h2 class="h4 fw-bold mb-0">Current lineup</h2></div><span class="small text-secondary"><?php echo e($tournament->teams_count); ?> teams</span></div><div class="row g-2"><?php $__empty_1 = true; $__currentLoopData = $tournament->teams; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $team): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="col-md-6"><div class="p-3 rounded-3 bg-light border h-100"><div class="fw-bold"><?php echo e($team->name); ?></div><div class="small text-secondary"><?php echo e($team->activeCaptain?->user?->name ?: 'Captain not assigned'); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="col-12 text-secondary">No teams configured.</div><?php endif; ?></div></div></div></div>
        <div class="row g-4"><div class="col-xl-6"><div class="cricket-surface overflow-hidden"><div class="p-4 border-bottom"><p class="cricket-kicker mb-1">Schedule oversight</p><h2 class="h4 fw-bold mb-0">Fixtures</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Match</th><th>Status</th><th>Scheduled</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $tournament->fixtures; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $fixture): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($fixture->homeTeam?->short_name ?: $fixture->homeTeam?->name ?: 'TBD'); ?> <span class="text-secondary">vs</span> <?php echo e($fixture->awayTeam?->short_name ?: $fixture->awayTeam?->name ?: 'TBD'); ?></td><td><span class="badge text-bg-light"><?php echo e(ucfirst($fixture->status)); ?></span></td><td class="text-secondary"><?php echo e($fixture->scheduled_at?->format('d M Y H:i') ?: 'Not scheduled'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="3" class="text-center py-4 text-secondary">No fixtures configured.</td></tr><?php endif; ?></tbody></table></div></div></div><div class="col-xl-6"><div class="cricket-surface overflow-hidden"><div class="p-4 border-bottom"><p class="cricket-kicker mb-1">Match operations</p><h2 class="h4 fw-bold mb-0">Matches</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Match</th><th>Status</th><th>Result</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $tournament->matches; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $match): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($match->fixture?->homeTeam?->short_name ?: $match->fixture?->homeTeam?->name ?: 'TBD'); ?> <span class="text-secondary">vs</span> <?php echo e($match->fixture?->awayTeam?->short_name ?: $match->fixture?->awayTeam?->name ?: 'TBD'); ?></td><td><span class="badge <?php echo e($match->status === 'live' ? 'text-bg-success' : 'text-bg-light'); ?>"><?php echo e(ucfirst($match->status)); ?></span></td><td class="text-secondary"><?php echo e($match->result_summary ?: 'Pending'); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="3" class="text-center py-4 text-secondary">No operational matches configured.</td></tr><?php endif; ?></tbody></table></div></div></div></div>
        <div class="cricket-surface overflow-hidden mt-4"><div class="p-4 border-bottom"><p class="cricket-kicker mb-1">Security trail</p><h2 class="h4 fw-bold mb-0">Tournament audit activity</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Action</th><th>Actor</th><th>Time</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $tournament->auditLogs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><span class="badge text-bg-light"><?php echo e($log->action); ?></span></td><td><?php echo e($log->user?->name ?: 'System'); ?></td><td class="text-secondary"><?php echo e($log->created_at?->format('d M Y H:i:s')); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="3" class="text-center py-4 text-secondary">No tournament audit activity found.</td></tr><?php endif; ?></tbody></table></div></div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/super-admin/tournaments/show.blade.php ENDPATH**/ ?>