<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> <div class="d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3"><div><p class="cricket-kicker mb-2">Tournament setup</p><h1 class="display-6 fw-bold mb-2">Player approvals</h1><p class="text-secondary mb-0"><?php echo e($tournament->name); ?> · Build the pool captains can actually pick from.</p></div><a href="<?php echo e(route('admin.tournaments.show', $tournament)); ?>" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Tournament workspace</a></div> <?php $__env->endSlot(); ?>

    <div class="container pb-5"><?php if(session('status')): ?><div class="alert alert-success border-0 shadow-sm"><?php echo e(session('status')); ?></div><?php endif; ?> <?php if($errors->any()): ?><div class="alert alert-danger border-0 shadow-sm"><strong>CSV import could not be completed.</strong><ul class="mb-0 mt-2"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?><div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4"><div><p class="cricket-kicker mb-1">Registration queue</p><h2 class="h3 fw-bold mb-0">Review players</h2></div><span class="badge text-bg-light"><?php echo e($registrations->total()); ?> registrations</span></div>
        <div class="cricket-surface p-3 p-lg-4 mb-4"><div class="row align-items-center g-4"><div class="col-lg-7"><p class="cricket-kicker mb-1">Bulk onboarding</p><h3 class="h4 fw-bold mb-2">Add players from CSV</h3><p class="text-secondary mb-0">Upload the provided template to create player profiles and approved tournament registrations in one transaction. Existing players are matched by phone number instead of duplicated.</p></div><div class="col-lg-5"><div class="d-flex flex-wrap justify-content-lg-end gap-2 mb-3"><a href="<?php echo e(route('admin.players.import.template')); ?>" class="btn btn-outline-primary"><i class="fa-solid fa-download me-2"></i>Download demo CSV</a></div><form method="POST" action="<?php echo e(route('admin.tournaments.players.import', $tournament)); ?>" enctype="multipart/form-data" class="d-flex flex-column flex-sm-row gap-2"><?php echo csrf_field(); ?><input type="file" name="players_csv" accept=".csv,text/csv" class="form-control" required><button class="btn btn-success flex-shrink-0" type="submit"><i class="fa-solid fa-upload me-2"></i>Upload CSV</button></form></div></div><div class="small text-secondary mt-3">Required columns: <code>full_name, phone, location, playing_role</code>. Supported roles: Batter, Bowler, All-rounder, Wicketkeeper. Maximum 500 rows per upload.</div></div>
        <div class="cricket-surface p-3 p-lg-4"><?php if($registrations->isEmpty()): ?><div class="p-5 text-center"><span class="cricket-brand-mark mb-4"><i class="fa-solid fa-user-check"></i></span><h3 class="h4 fw-bold">The queue is clear</h3><p class="text-secondary mb-0">No player registrations are waiting for review.</p></div><?php else: ?><div class="vstack gap-2"><?php $__currentLoopData = $registrations; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $registration): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cricket-surface-soft p-3 p-lg-4"><div class="row align-items-center g-3"><div class="col-lg-4"><div class="d-flex align-items-center gap-3"><span class="cricket-brand-mark flex-shrink-0"><i class="fa-solid fa-user"></i></span><div><div class="fw-bold"><?php echo e($registration->playerProfile?->full_name); ?></div><div class="small text-secondary"><?php echo e($registration->playerProfile?->user?->email); ?></div></div></div></div><div class="col-6 col-lg-2"><div class="small text-secondary mb-1">Playing role</div><div class="fw-bold"><?php echo e($registration->playerProfile?->playing_role ?: 'Not set'); ?></div></div><div class="col-6 col-lg-2"><div class="small text-secondary mb-1">City</div><div class="fw-bold"><?php echo e($registration->playerProfile?->city ?: 'Not set'); ?></div></div><div class="col-6 col-lg-2"><div class="small text-secondary mb-1">Status</div><span class="badge <?php echo e($registration->status === 'approved' ? 'text-bg-success' : ($registration->status === 'rejected' ? 'text-bg-danger' : 'text-bg-warning')); ?>"><?php echo e(ucfirst($registration->status)); ?></span></div><div class="col-6 col-lg-2"><div class="d-flex justify-content-lg-end gap-2"><?php if($registration->status !== 'approved'): ?><form method="POST" action="<?php echo e(route('admin.tournaments.players.approve', [$tournament, $registration])); ?>"><?php echo csrf_field(); ?><button class="btn btn-sm btn-success" type="submit"><i class="fa-solid fa-check me-1"></i>Approve</button></form><?php endif; ?> <?php if($registration->status !== 'rejected'): ?><form method="POST" action="<?php echo e(route('admin.tournaments.players.reject', [$tournament, $registration])); ?>"><?php echo csrf_field(); ?><button class="btn btn-sm btn-light text-danger" type="submit"><i class="fa-solid fa-xmark me-1"></i>Reject</button></form><?php endif; ?></div></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><div class="mt-4"><?php echo e($registrations->links()); ?></div><?php endif; ?></div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/admin/tournaments/players.blade.php ENDPATH**/ ?>