<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> 
        <div class="d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3"><div><p class="cricket-kicker mb-2">Captain reports</p><h1 class="display-6 fw-bold mb-2"><?php echo e($report['tournament']->name); ?></h1><p class="text-secondary mb-0">Your team’s squad, draft history, tournament summary, and timer status.</p></div><a href="<?php echo e(route('captain.dashboard')); ?>" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Captain dashboard</a></div>
     <?php $__env->endSlot(); ?>
    <div class="container pb-5">
        <div class="cricket-pitch-panel p-4 p-lg-5 mb-4"><p class="cricket-kicker mb-2">Team report</p><h2 class="h2 fw-bold mb-2"><?php echo e($report['captain_team'] ?: 'Assigned team'); ?></h2><p class="text-white-50 mb-0">Captain-only view. Internal registrations, audit IPs, and other teams’ private actions are not included.</p></div>
        <div class="row g-3 mb-4"><?php $__currentLoopData = [['selected_players','Your selected players'],['total_picks','Draft picks'],['completed_picks','Completed picks'],['extended_seconds','Extended seconds']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$key,$label]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-6 col-lg-3"><div class="cricket-surface p-3"><div class="small text-secondary"><?php echo e($label); ?></div><div class="cricket-stat-value mt-2"><?php echo e($report['summary'][$key] ?? $report['timer'][$key] ?? 0); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
        <div class="cricket-surface p-4 p-lg-5 mb-4"><div class="d-flex align-items-center justify-content-between gap-3 mb-4"><div><p class="cricket-kicker mb-2">Download center</p><h2 class="h3 fw-bold mb-1">Captain reports</h2><p class="text-secondary mb-0">Download the reports relevant to your team.</p></div><i class="fa-solid fa-file-pdf text-danger fs-2"></i></div><div class="row g-3"><?php $__currentLoopData = $reportTypes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-md-6 col-lg-3"><div class="cricket-surface-soft p-3 h-100 d-flex flex-column"><div class="fw-bold"><?php echo e($label); ?></div><div class="small text-secondary mb-3">PDF download</div><a href="<?php echo e(route('captain.reports.pdf', [$report['tournament'], $type])); ?>" class="btn btn-outline-danger btn-sm mt-auto"><i class="fa-solid fa-download me-1"></i>Download PDF</a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div>
        <div class="row g-4"><div class="col-xl-6"><div class="cricket-surface p-4 h-100"><h2 class="h4 fw-bold mb-3">Your team squad</h2><div class="vstack gap-2"><?php $__empty_1 = true; $__currentLoopData = $report['team_squads']->first()['players'] ?? []; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $player): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="cricket-surface-soft p-3 d-flex justify-content-between"><span class="fw-bold"><?php echo e($player['player']); ?></span><span class="small text-secondary"><?php echo e($player['playing_role'] ?: 'Unassigned'); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="text-secondary">No player has been selected for your team yet.</div><?php endif; ?></div></div></div><div class="col-xl-6"><div class="cricket-surface p-4 h-100"><h2 class="h4 fw-bold mb-3">Your pick history</h2><div class="vstack gap-2"><?php $__empty_1 = true; $__currentLoopData = $report['history']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pick): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="cricket-surface-soft p-3 d-flex justify-content-between"><span><strong>#<?php echo e($pick['pick_number']); ?></strong> · <?php echo e($pick['player'] ?: '—'); ?></span><span class="small text-secondary"><?php echo e(ucfirst($pick['status'])); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div class="text-secondary">No picks recorded for your team yet.</div><?php endif; ?></div></div></div></div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/captain/reports/index.blade.php ENDPATH**/ ?>