<?php if (isset($component)) { $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.public-layout','data' => ['title' => ''.e($report['tournament']->name).' Reports · Cricket Draft OS']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('public-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => ''.e($report['tournament']->name).' Reports · Cricket Draft OS']); ?>
    <main class="container py-5"><div class="d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3 mb-5"><div><p class="cricket-kicker mb-2">Public reports</p><h1 class="display-5 fw-bold mb-2"><?php echo e($report['tournament']->name); ?></h1><p class="lead text-secondary mb-0">Safe spectator reports with team squads, pick history, and public draft status.</p></div><span class="badge text-bg-success"><?php echo e(ucfirst($report['summary']['draft_status'])); ?></span></div>
        <div class="cricket-surface p-4 p-lg-5 mb-4"><div class="d-flex align-items-center justify-content-between gap-3 mb-4"><div><p class="cricket-kicker mb-2">Download center</p><h2 class="h3 fw-bold mb-1">Public reports</h2><p class="text-secondary mb-0">Private registrations, audit logs, IP addresses, and user agents are never included.</p></div><i class="fa-solid fa-file-pdf text-danger fs-2"></i></div><div class="row g-3"><?php $__currentLoopData = $reportTypes; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-md-6 col-lg-3"><div class="cricket-surface-soft p-3 h-100 d-flex flex-column"><div class="fw-bold"><?php echo e($label); ?></div><div class="small text-secondary mb-3">PDF download</div><a href="<?php echo e(route('public.reports.pdf', [$report['tournament'], $type])); ?>" class="btn btn-outline-danger btn-sm mt-auto"><i class="fa-solid fa-download me-1"></i>Download PDF</a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div>
        <div class="row g-3 mb-4"><?php $__currentLoopData = [['teams','Teams'],['selected_players','Selected players'],['total_picks','Total picks'],['completed_picks','Completed picks']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$key,$label]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-6 col-lg-3"><div class="cricket-surface p-3"><div class="small text-secondary"><?php echo e($label); ?></div><div class="cricket-stat-value mt-2"><?php echo e($report['summary'][$key]); ?></div></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
        <div class="row g-4"><div class="col-xl-7"><div class="cricket-surface p-4 h-100"><h2 class="h4 fw-bold mb-3">Team squads</h2><div class="vstack gap-3"><?php $__currentLoopData = $report['team_squads']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $squad): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cricket-surface-soft p-3"><div class="d-flex justify-content-between"><strong><?php echo e($squad['team']); ?></strong><span class="badge text-bg-success"><?php echo e($squad['selected_count']); ?></span></div><div class="small text-secondary mt-2"><?php $__empty_1 = true; $__currentLoopData = $squad['players']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $player): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><?php echo e($player['player']); ?> · <?php echo e($player['playing_role'] ?: 'Unassigned'); ?><?php if(!$loop->last): ?>, <?php endif; ?> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?> No player selected yet. <?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div></div><div class="col-xl-5"><div class="cricket-surface p-4 h-100"><h2 class="h4 fw-bold mb-3">Pick history</h2><div class="vstack gap-2"><?php $__currentLoopData = $report['history']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pick): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="cricket-surface-soft p-3 d-flex justify-content-between"><span><strong>#<?php echo e($pick['pick_number']); ?></strong> · <?php echo e($pick['team']); ?></span><span class="small text-secondary"><?php echo e($pick['player'] ?: ucfirst($pick['status'])); ?></span></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div></div></div>
    </main>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $attributes = $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $component = $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/public/reports/show.blade.php ENDPATH**/ ?>