<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">Security governance</p><h1 class="display-6 fw-bold mb-2">Global audit explorer</h1><p class="text-secondary mb-0">Search the complete platform trail by actor, action, tournament, IP address, or date range.</p></div><div class="d-flex gap-2"><a href="<?php echo e(route('super-admin.audit-logs.export', request()->query())); ?>" class="btn btn-success"><i class="fa-solid fa-download me-2"></i>Export CSV</a><a href="<?php echo e(route('super-admin.dashboard')); ?>" class="btn btn-light">Control plane</a></div></div> <?php $__env->endSlot(); ?>
    <div class="container pb-5">
        <div class="cricket-surface p-4 mb-4"><form method="GET" class="row g-2 align-items-end"><div class="col-lg-4"><label class="form-label small text-secondary">Search</label><input type="search" name="search" value="<?php echo e($search); ?>" class="form-control" placeholder="Action, actor, email, tournament, or IP"></div><div class="col-lg-3"><label class="form-label small text-secondary">Action</label><select name="action" class="form-select"><option value="">All actions</option><?php $__currentLoopData = $actions; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $action): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($action); ?>" <?php if($selectedAction === $action): echo 'selected'; endif; ?>><?php echo e($action); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-lg-2"><label class="form-label small text-secondary">From</label><input type="date" name="from" value="<?php echo e($from); ?>" class="form-control"></div><div class="col-lg-2"><label class="form-label small text-secondary">To</label><input type="date" name="to" value="<?php echo e($to); ?>" class="form-control"></div><div class="col-lg-1 d-flex gap-2"><button class="btn btn-success flex-grow-1"><i class="fa-solid fa-filter"></i></button></div><div class="col-12"><a href="<?php echo e(route('super-admin.audit-logs.index')); ?>" class="small text-secondary">Reset filters</a></div></form></div>
        <div class="cricket-surface overflow-hidden"><div class="d-flex justify-content-between align-items-center gap-3 p-4 border-bottom"><div><p class="cricket-kicker mb-1">Immutable operational trail</p><h2 class="h4 fw-bold mb-0">Audit events</h2></div><span class="small text-secondary"><?php echo e($logs->total()); ?> matching events</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Scope</th><th>Network</th><th>Metadata</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $logs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="text-secondary text-nowrap"><?php echo e($log->created_at?->format('d M Y H:i:s')); ?></td><td><span class="badge text-bg-light"><?php echo e($log->action); ?></span></td><td><?php echo e($log->user?->name ?: 'System'); ?><div class="small text-secondary"><?php echo e($log->user?->email); ?></div></td><td><?php echo e($log->tournament?->name ?: ($log->auditable_type ? class_basename($log->auditable_type).' #'.$log->auditable_id : 'Platform')); ?></td><td class="small text-secondary"><?php echo e($log->ip_address ?: '—'); ?><div class="text-truncate" style="max-width: 180px;" title="<?php echo e($log->user_agent); ?>"><?php echo e($log->user_agent ?: 'No user agent'); ?></div></td><td><code class="small"><?php echo e($log->metadata ? json_encode($log->metadata, JSON_UNESCAPED_SLASHES) : '—'); ?></code></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center py-5 text-secondary">No audit records match the selected filters.</td></tr><?php endif; ?></tbody></table></div></div><div class="mt-3"><?php echo e($logs->links()); ?></div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/super-admin/audit-logs/index.blade.php ENDPATH**/ ?>