<?php if (isset($component)) { $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.public-layout','data' => ['title' => 'Tournaments · Cricket Draft OS']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('public-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Tournaments · Cricket Draft OS']); ?>
    <section class="saas-page-hero"><div class="container py-5 py-lg-6"><div class="d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-4"><div><p class="cricket-kicker mb-2">Public tournament directory</p><h1 class="saas-page-title mb-3">Find the competition you want to follow.</h1><p class="lead text-secondary mb-0">Live boards, open registration, and completed tournaments are surfaced from the current platform state.</p></div><div class="saas-directory-summary"><strong><?php echo e($tournaments->count()); ?></strong><span>public events</span></div></div></div></section>

    <section class="container pb-5"><div class="row g-4"><div class="col-lg-8"><div class="d-flex align-items-center gap-2 mb-4"><span class="saas-section-marker bg-success"></span><h2 class="h4 fw-bold mb-0">Live now</h2><span class="badge text-bg-success"><?php echo e($liveTournaments->count()); ?></span></div><?php if($liveTournaments->isEmpty()): ?><div class="saas-empty-state mb-5"><span class="saas-avatar"><i class="fa-solid fa-tower-broadcast"></i></span><div><h3 class="h5 fw-bold">No tournament is live right now</h3><p class="text-secondary mb-0">When an admin starts a draft, its live board will appear here automatically.</p></div></div><?php else: ?><div class="row g-4 mb-5"><?php $__currentLoopData = $liveTournaments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $tournament = $item['tournament']; $state = $item['state']; $summary = $state['summary']; $progress = $summary['total'] > 0 ? round(($summary['selected'] / $summary['total']) * 100) : 0; ?><div class="col-md-6"><div class="saas-directory-card saas-directory-card-live h-100"><div class="d-flex justify-content-between align-items-start mb-4"><span class="saas-avatar"><i class="fa-solid fa-tower-broadcast"></i></span><span class="badge bg-lime text-dark">Live now</span></div><h3 class="h5 fw-bold mb-1"><?php echo e($tournament->name); ?></h3><div class="small text-secondary mb-4"><?php echo e($tournament->season_name ?: 'Current season'); ?> · <?php echo e($item['teams_count']); ?> teams</div><div class="small text-secondary d-flex justify-content-between"><span>On the clock</span><strong class="text-dark"><?php echo e($state['current_team']['name'] ?? 'Waiting'); ?></strong></div><div class="progress mt-3" style="height:.4rem;"><div class="progress-bar bg-success" style="width:<?php echo e($progress); ?>%;"></div></div><a href="<?php echo e(route('public.draft.show', $tournament)); ?>" class="btn btn-success w-100 mt-4">Open live board <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?>

    <div class="d-flex align-items-center gap-2 mb-4"><span class="saas-section-marker bg-warning"></span><h2 class="h4 fw-bold mb-0">Open registration</h2><span class="badge text-bg-light"><?php echo e($registrationTournaments->count()); ?></span></div><?php if($registrationTournaments->isEmpty()): ?><div class="saas-empty-state mb-5"><span class="saas-avatar"><i class="fa-solid fa-calendar-check"></i></span><div><h3 class="h5 fw-bold">No registration window is open</h3><p class="text-secondary mb-0">Check back when an administrator moves a tournament into registration.</p></div></div><?php else: ?><div class="row g-4 mb-5"><?php $__currentLoopData = $registrationTournaments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $tournament = $item['tournament']; ?><div class="col-md-6"><div class="saas-directory-card h-100"><div class="d-flex justify-content-between align-items-start mb-4"><span class="saas-avatar"><i class="fa-solid fa-user-plus"></i></span><span class="badge text-bg-light"><?php echo e(ucfirst($tournament->status)); ?></span></div><h3 class="h5 fw-bold mb-1"><?php echo e($tournament->name); ?></h3><div class="small text-success fw-bold mb-2"><?php echo e($tournament->season_name ?: 'Tournament season'); ?></div><p class="small text-secondary mb-4"><?php echo e($tournament->venue ?: $tournament->location ?: 'Location to be announced'); ?><?php echo e($tournament->city ? ', '.$tournament->city : ''); ?></p><div class="d-flex justify-content-between small text-secondary mb-4"><span>Approved players</span><strong class="text-dark"><?php echo e($item['approved_players_count']); ?></strong></div><a href="<?php echo e(auth()->check() && auth()->user()->hasRole('player') ? route('player.tournaments.index') : route('register')); ?>" class="btn btn-outline-success w-100">Register interest <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?>

    <div class="d-flex align-items-center gap-2 mb-4"><span class="saas-section-marker bg-secondary"></span><h2 class="h4 fw-bold mb-0">Completed archive</h2><span class="badge text-bg-light"><?php echo e($completedTournaments->count()); ?></span></div><?php if($completedTournaments->isEmpty()): ?><div class="saas-empty-state"><span class="saas-avatar"><i class="fa-solid fa-box-archive"></i></span><div><h3 class="h5 fw-bold">No completed tournaments yet</h3><p class="text-secondary mb-0">Completed public events will become a read-only archive here.</p></div></div><?php else: ?><div class="row g-4"><?php $__currentLoopData = $completedTournaments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php $tournament = $item['tournament']; ?><div class="col-md-6"><div class="saas-directory-card h-100"><div class="d-flex justify-content-between align-items-start mb-4"><span class="saas-avatar"><i class="fa-solid fa-flag-checkered"></i></span><span class="badge text-bg-light">Completed</span></div><h3 class="h5 fw-bold mb-1"><?php echo e($tournament->name); ?></h3><div class="small text-secondary mb-4"><?php echo e($tournament->season_name ?: 'Historical season'); ?> · <?php echo e($item['teams_count']); ?> teams</div><a href="<?php echo e(route('public.reports.show', $tournament)); ?>" class="btn btn-light w-100">Open public reports <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?></div><div class="col-lg-4"><div class="saas-sidebar-card sticky-lg-top"><p class="cricket-kicker mb-2">What you can follow</p><h2 class="h4 fw-bold mb-3">One public view for the whole competition.</h2><div class="vstack gap-3"><div class="d-flex gap-3"><span class="saas-mini-icon"><i class="fa-solid fa-shuffle"></i></span><div><div class="fw-bold">Live draft boards</div><div class="small text-secondary">Timer, current team, picks, and squad progress.</div></div></div><div class="d-flex gap-3"><span class="saas-mini-icon"><i class="fa-solid fa-calendar-days"></i></span><div><div class="fw-bold">Match centers</div><div class="small text-secondary">Fixtures, venues, statuses, and scorecard links.</div></div></div><div class="d-flex gap-3"><span class="saas-mini-icon"><i class="fa-solid fa-chart-column"></i></span><div><div class="fw-bold">Standings and reports</div><div class="small text-secondary">Points tables, public summaries, and downloads.</div></div></div></div><a href="<?php echo e(route('public.features')); ?>" class="btn btn-outline-success w-100 mt-4">Explore platform features</a></div></div></div></section>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $attributes = $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $component = $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/public/tournaments/index.blade.php ENDPATH**/ ?>