<?php if($errors->any()): ?><div class="alert alert-danger border-0 shadow-sm"><ul class="mb-0"><?php $__currentLoopData = $errors->all(); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $error): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li><?php echo e($error); ?></li><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></ul></div><?php endif; ?>
<form method="POST" action="<?php echo e($action); ?>" class="cricket-surface p-4 p-lg-5">
    <?php echo csrf_field(); ?>
    <?php if(($method ?? 'POST') !== 'POST'): ?> <?php echo method_field($method); ?> <?php endif; ?>
    <div class="row g-4">
        <div class="col-md-6"><label class="form-label fw-semibold" for="home_team_id">Home team</label><select class="form-select" id="home_team_id" name="home_team_id" required><option value="">Select home team</option><?php $__currentLoopData = $teams; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $team): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($team->id); ?>" <?php if((string) old('home_team_id', $fixture->home_team_id) === (string) $team->id): echo 'selected'; endif; ?>><?php echo e($team->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="away_team_id">Away team</label><select class="form-select" id="away_team_id" name="away_team_id" required><option value="">Select away team</option><?php $__currentLoopData = $teams; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $team): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($team->id); ?>" <?php if((string) old('away_team_id', $fixture->away_team_id) === (string) $team->id): echo 'selected'; endif; ?>><?php echo e($team->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        <div class="col-md-4"><label class="form-label fw-semibold" for="round_number">Round number</label><input class="form-control" id="round_number" name="round_number" type="number" min="1" value="<?php echo e(old('round_number', $fixture->round_number)); ?>"></div>
        <div class="col-md-8"><label class="form-label fw-semibold" for="round_name">Round name</label><input class="form-control" id="round_name" name="round_name" value="<?php echo e(old('round_name', $fixture->round_name)); ?>" placeholder="Group stage, semifinal, final"></div>
        <div class="col-md-4"><label class="form-label fw-semibold" for="match_number">Match number</label><input class="form-control" id="match_number" name="match_number" type="number" min="1" value="<?php echo e(old('match_number', $fixture->match_number)); ?>" placeholder="Optional"></div>
        <div class="col-md-8"><label class="form-label fw-semibold" for="scheduled_at">Scheduled date and time</label><input class="form-control" id="scheduled_at" name="scheduled_at" type="datetime-local" required value="<?php echo e(old('scheduled_at', $fixture->scheduled_at ? $fixture->scheduled_at->setTimezone($fixture->timezone ?: $tournament->timezone)->format('Y-m-d\\TH:i') : '')); ?>"></div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="venue">Venue</label><input class="form-control" id="venue" name="venue" value="<?php echo e(old('venue', $fixture->venue ?: $tournament->venue)); ?>" placeholder="Cricket ground or stadium"></div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="city">City</label><input class="form-control" id="city" name="city" value="<?php echo e(old('city', $fixture->city ?: $tournament->city)); ?>"></div>
        <div class="col-md-6"><label class="form-label fw-semibold" for="timezone">Timezone</label><input class="form-control" id="timezone" name="timezone" list="fixture-timezones" required value="<?php echo e(old('timezone', $fixture->timezone ?: $tournament->timezone ?: 'UTC')); ?>"><datalist id="fixture-timezones"><option value="Asia/Karachi"><option value="UTC"><option value="Asia/Dubai"><option value="Asia/Kolkata"><option value="Europe/London"></datalist></div>
        <div class="col-12"><label class="form-label fw-semibold" for="notes">Notes</label><textarea class="form-control" id="notes" name="notes" rows="3" placeholder="Optional match notes"><?php echo e(old('notes', $fixture->notes)); ?></textarea></div>
    </div>
    <div class="d-flex justify-content-end gap-2 mt-4"><a href="<?php echo e(route('admin.tournaments.fixtures.index', $tournament)); ?>" class="btn btn-light">Cancel</a><button type="submit" class="btn btn-success"><i class="fa-solid fa-calendar-plus me-2"></i><?php echo e(($method ?? 'POST') === 'POST' ? 'Create fixture' : 'Save changes'); ?></button></div>
</form>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/admin/fixtures/_form.blade.php ENDPATH**/ ?>