<?php if (isset($component)) { $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.public-layout','data' => ['title' => 'How it works · Cricket Draft OS']] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('public-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'How it works · Cricket Draft OS']); ?>
    <section class="saas-page-hero">
        <div class="container py-5 py-lg-6"><div class="row align-items-center g-5"><div class="col-lg-7"><p class="cricket-kicker mb-2">How it works</p><h1 class="saas-page-title mb-3">One clean operating flow from registration to result.</h1><p class="lead text-secondary mb-0">Different people can operate different parts of the tournament without losing a shared view of what is happening now, what happened before, and what happens next.</p></div><div class="col-lg-5"><div class="saas-flow-summary"><div class="small text-uppercase text-secondary fw-bold mb-3" style="letter-spacing:.12em;">The operating model</div><div class="d-flex align-items-center gap-3"><span class="saas-flow-node">01</span><span class="fw-bold">Configure → draft → schedule → score</span></div><div class="saas-flow-line"></div><div class="d-flex align-items-center gap-3"><span class="saas-flow-node">02</span><span class="fw-bold">Publish the same authoritative state</span></div></div></div></div></div>
    </section>
    <section class="container py-5"><div class="row g-4"><div class="col-lg-3 col-md-6"><div class="saas-step-card h-100"><span class="saas-step-number">01</span><h2 class="h5 fw-bold">Set the rules</h2><p class="small text-secondary mb-0">Create the season and tournament, define teams and squad size, set registration windows, and choose the default overs format.</p></div></div><div class="col-lg-3 col-md-6"><div class="saas-step-card h-100"><span class="saas-step-number">02</span><h2 class="h5 fw-bold">Build the squads</h2><p class="small text-secondary mb-0">Import or approve players, configure draft rounds, assign every pick, and let captains select through their role-aware room.</p></div></div><div class="col-lg-3 col-md-6"><div class="saas-step-card h-100"><span class="saas-step-number">03</span><h2 class="h5 fw-bold">Make the fixtures</h2><p class="small text-secondary mb-0">Schedule matchups, set venues and times, create squad snapshots, choose playing XIs, approve lineups, and record the toss.</p></div></div><div class="col-lg-3 col-md-6"><div class="saas-step-card h-100"><span class="saas-step-number">04</span><h2 class="h5 fw-bold">Score and publish</h2><p class="small text-secondary mb-0">Capture every delivery, move through innings, approve the result, update standings, and expose live scorecards and reports.</p></div></div></div></section>
    <section class="container pb-5"><div class="row g-4"><div class="col-lg-6"><div class="saas-role-panel"><div class="saas-feature-icon"><i class="fa-solid fa-shield-halved"></i></div><h2 class="h4 fw-bold">For tournament operators</h2><p class="text-secondary">Use a central control plane for governance, lifecycle changes, timer actions, player approvals, match status, reports, and audit visibility.</p><a href="<?php echo e(route('login')); ?>" class="btn btn-outline-success">Open operator login <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div><div class="col-lg-6"><div class="saas-role-panel"><div class="saas-feature-icon"><i class="fa-solid fa-tower-broadcast"></i></div><h2 class="h4 fw-bold">For players and fans</h2><p class="text-secondary">Browse public tournaments, register as a player, watch the live draft, follow fixtures, read scorecards, and download public reports.</p><a href="<?php echo e(route('public.tournaments.index')); ?>" class="btn btn-success">Explore public tournaments <i class="fa-solid fa-arrow-right ms-2"></i></a></div></div></div></section>
    <section class="saas-dark-section py-5"><div class="container py-lg-4 text-center"><p class="cricket-kicker text-lime mb-2">Always in sync</p><h2 class="saas-section-title text-white mx-auto mb-3" style="max-width: 52rem;">The web app, mobile app, and public audience all read the same backend truth.</h2><p class="text-white-50 mx-auto mb-4" style="max-width: 42rem;">That means fewer screenshots, fewer manual updates, and a better match-day experience for everyone involved.</p><a href="<?php echo e(route('public.features')); ?>" class="btn btn-lime">Explore the platform <i class="fa-solid fa-arrow-right ms-2"></i></a></div></section>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $attributes = $__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__attributesOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b)): ?>
<?php $component = $__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b; ?>
<?php unset($__componentOriginal58c831a7c3cbf004f2e66a23aed50e5b); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/public/how-it-works.blade.php ENDPATH**/ ?>