<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">Platform operations</p><h1 class="display-6 fw-bold mb-2">Tournament fleet</h1><p class="text-secondary mb-0">Monitor every season, registration window, fixture schedule, live match room, and completion state from one platform-wide view.</p></div><a href="<?php echo e(route('super-admin.dashboard')); ?>" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Control plane</a></div> <?php $__env->endSlot(); ?>
    <div class="container pb-5">
        <div class="row g-2 mb-4"><?php $__currentLoopData = ['draft' => 'Draft', 'registration' => 'Registration', 'ready' => 'Ready', 'live' => 'Live', 'completed' => 'Completed', 'cancelled' => 'Cancelled']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status => $label): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-6 col-md-4 col-xl-2"><a href="<?php echo e(route('super-admin.tournaments.index', ['status' => $status])); ?>" class="cricket-surface p-3 h-100 text-decoration-none d-block"><div class="small text-secondary"><?php echo e($label); ?></div><div class="h3 fw-bold text-dark mb-0"><?php echo e($statusCounts[$status] ?? 0); ?></div></a></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
        <div class="cricket-surface p-4 mb-4"><form method="GET" class="row g-2 align-items-end"><div class="col-lg-7"><label class="form-label small text-secondary">Search tournament fleet</label><input type="search" name="search" value="<?php echo e($search); ?>" class="form-control" placeholder="Name, season, city, or venue"></div><div class="col-lg-3"><label class="form-label small text-secondary">Lifecycle status</label><select name="status" class="form-select"><option value="">All statuses</option><?php $__currentLoopData = $statuses; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status); ?>" <?php if($selectedStatus === $status): echo 'selected'; endif; ?>><?php echo e(ucfirst($status)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-success flex-grow-1">Filter</button><a href="<?php echo e(route('super-admin.tournaments.index')); ?>" class="btn btn-light">Reset</a></div></form></div>
        <div class="cricket-surface overflow-hidden"><div class="d-flex justify-content-between align-items-center gap-3 p-4 border-bottom"><div><p class="cricket-kicker mb-1">Competition directory</p><h2 class="h4 fw-bold mb-0">All tournaments</h2></div><span class="small text-secondary"><?php echo e($tournaments->total()); ?> total matches</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Tournament</th><th>Status</th><th>Teams</th><th>Players</th><th>Fixtures</th><th>Matches</th><th class="text-end">Action</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $tournaments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $tournament): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><div class="fw-semibold"><?php echo e($tournament->name); ?></div><div class="small text-secondary"><?php echo e($tournament->season_name ?: 'No season name'); ?> · <?php echo e($tournament->city ?: $tournament->venue ?: 'Location not set'); ?></div></td><td><span class="badge <?php echo e($tournament->status === 'live' ? 'text-bg-success' : ($tournament->status === 'completed' ? 'text-bg-dark' : 'text-bg-light')); ?>"><?php echo e(ucfirst($tournament->status)); ?></span><div class="small text-secondary mt-1"><?php echo e($tournament->is_public ? 'Public' : 'Private'); ?></div></td><td><?php echo e($tournament->teams_count); ?></td><td><?php echo e($tournament->tournament_players_count); ?></td><td><?php echo e($tournament->fixtures_count); ?></td><td><?php echo e($tournament->matches_count); ?></td><td class="text-end"><a href="<?php echo e(route('super-admin.tournaments.show', $tournament)); ?>" class="btn btn-sm btn-outline-success">Inspect</a></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center py-5 text-secondary">No tournaments match the selected filters.</td></tr><?php endif; ?></tbody></table></div></div><div class="mt-3"><?php echo e($tournaments->links()); ?></div>
    </div>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH C:\Users\Muhammad Aliyan\Downloads\cricket-draft-source\resources\views/super-admin/tournaments/index.blade.php ENDPATH**/ ?>