<x-app-layout>
    <x-slot name="header"><div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-end gap-3"><div><p class="cricket-kicker mb-2">API governance</p><h1 class="display-6 fw-bold mb-2">API sessions</h1><p class="text-secondary mb-0">Review device tokens, identify stale access, and contain compromised sessions without touching user records.</p></div><a href="{{ route('super-admin.dashboard') }}" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Control plane</a></div></x-slot>
    <div class="container pb-5">
        @if(session('status'))<div class="alert alert-success border-0 shadow-sm">{{ session('status') }}</div>@endif
        <div class="row g-3 mb-4"><div class="col-md-4"><div class="cricket-surface p-4 h-100"><div class="small text-secondary">Active sessions</div><div class="display-6 fw-bold text-success">{{ $activeCount }}</div><div class="small text-secondary">No expiry or expiry in the future</div></div></div><div class="col-md-4"><div class="cricket-surface p-4 h-100"><div class="small text-secondary">Expired sessions</div><div class="display-6 fw-bold">{{ $expiredCount }}</div><div class="small text-secondary">Retained until cleanup</div></div></div><div class="col-md-4"><div class="cricket-surface p-4 h-100 d-flex flex-column justify-content-between"><div><div class="small text-secondary">Containment</div><div class="fw-semibold">Remove stale credentials</div></div><form method="POST" action="{{ route('super-admin.api-sessions.revoke-expired') }}" class="mt-3">@csrf<button class="btn btn-outline-danger w-100" onclick="return confirm('Revoke all expired API sessions?')"><i class="fa-solid fa-broom me-2"></i>Revoke expired</button></form></div></div></div>
        <div class="cricket-surface p-4 mb-4"><form method="GET" class="row g-2 align-items-end"><div class="col-lg-7"><label class="form-label small text-secondary">Search device or user</label><input type="search" name="search" value="{{ $search }}" class="form-control" placeholder="Token name, user name, or email"></div><div class="col-lg-3"><label class="form-label small text-secondary">Session status</label><select name="status" class="form-select"><option value="">All sessions</option><option value="active" @selected($selectedStatus === 'active')>Active</option><option value="expired" @selected($selectedStatus === 'expired')>Expired</option></select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-success flex-grow-1">Filter</button><a href="{{ route('super-admin.api-sessions.index') }}" class="btn btn-light">Reset</a></div></form></div>
        <div class="cricket-surface overflow-hidden"><div class="d-flex justify-content-between align-items-center gap-3 p-4 border-bottom"><div><p class="cricket-kicker mb-1">Session ledger</p><h2 class="h4 fw-bold mb-0">Device tokens</h2></div><span class="small text-secondary">{{ $sessions->total() }} total matches</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Token</th><th>User</th><th>Abilities</th><th>Last used</th><th>Expiry</th><th class="text-end">Action</th></tr></thead><tbody>@forelse($sessions as $session)@php $expired = $session->expires_at && $session->expires_at->isPast(); @endphp<tr><td><strong>{{ $session->name }}</strong><div class="small text-secondary">Token #{{ $session->id }}</div></td><td>{{ $session->tokenable?->name ?: 'Deleted user' }}<div class="small text-secondary">{{ $session->tokenable?->email }}</div></td><td><span class="small">{{ collect($session->abilities)->join(', ') ?: 'All abilities' }}</span></td><td class="text-secondary">{{ $session->last_used_at?->format('d M Y H:i') ?: 'Not used' }}</td><td><span class="badge {{ $expired ? 'text-bg-warning' : 'text-bg-success' }}">{{ $expired ? 'Expired' : 'Active' }}</span><div class="small text-secondary mt-1">{{ $session->expires_at?->format('d M Y H:i') ?: 'No expiry' }}</div></td><td class="text-end"><form method="POST" action="{{ route('super-admin.api-sessions.revoke', $session) }}" onsubmit="return confirm('Revoke this API session?')">@csrf @method('DELETE')<button type="submit" class="btn btn-sm btn-outline-danger">Revoke</button></form></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-secondary">No API sessions match the selected filters.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $sessions->links() }}</div>
    </div>
</x-app-layout>
