<x-app-layout>
    <x-slot name="header"><div class="d-flex flex-column flex-lg-row align-items-lg-end justify-content-between gap-3"><div><p class="cricket-kicker mb-2">Draft configuration</p><h1 class="display-6 fw-bold mb-2">Build the pick order.</h1><p class="text-secondary mb-0">{{ $tournament->name }} · Every slot is assigned to a specific team.</p></div><div class="d-flex gap-2"><span class="badge {{ $isLocked ? 'text-bg-warning' : 'text-bg-light' }}">{{ $isLocked ? 'Read-only · locked' : 'Setup only' }}</span>@if($draft->rounds->isNotEmpty())<a href="{{ route('admin.tournaments.draft.setup.pdf', $tournament) }}" class="btn btn-outline-success"><i class="fa-solid fa-file-pdf me-2"></i>Download PDF</a>@endif<a href="{{ route('admin.tournaments.show', $tournament) }}" class="btn btn-light"><i class="fa-solid fa-arrow-left me-2"></i>Tournament workspace</a></div></div></x-slot>

    <div class="container pb-5" x-data="draftSetupForm()">
        @if ($errors->any())<div class="alert alert-danger border-0 shadow-sm"><strong>Please correct the setup:</strong><ul class="mb-0 mt-2">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        @if ($isLocked)<div class="alert alert-warning border-0 shadow-sm"><i class="fa-solid fa-lock me-2"></i>This draft has started. Its round and pick configuration is locked, so this page is available for viewing only. Use the live control room for timer, pick, skip, undo, and manual override actions.</div>@endif
        <div class="cricket-pitch-panel p-4 mb-4"><div class="row align-items-center g-3"><div class="col-lg-8"><p class="cricket-kicker mb-2">Admin-defined sequence</p><h2 class="h3 fw-bold mb-2">No snake rules. No surprises.</h2><p class="text-white-50 mb-0">Assign each pick number to the exact team that should own it. The live board will follow this order.</p></div><div class="col-lg-4 text-lg-end"><i class="fa-solid fa-list-ol" style="font-size:4rem;color:var(--cricket-lime);opacity:.85;"></i></div></div></div>
        @if (!$isLocked && !$tournament->teams->isEmpty())
            <div class="cricket-surface p-4 mb-4"><div class="row g-4 align-items-center"><div class="col-md-6"><h3 class="h5 fw-bold mb-2"><i class="fa-solid fa-file-csv text-success me-2"></i>Quick Setup via CSV</h3><p class="text-secondary small mb-3">You can download our template, fill in your rounds and pick orders, and upload it here to set up the draft sequence in one click.</p><a href="{{ route('admin.tournaments.draft.setup.sample-csv', $tournament) }}" class="btn btn-sm btn-outline-success"><i class="fa-solid fa-download me-2"></i>Download Sample CSV Template</a></div><div class="col-md-6"><form method="POST" action="{{ route('admin.tournaments.draft.setup.import-csv', $tournament) }}" enctype="multipart/form-data" class="vstack gap-2">@csrf<label class="form-label small fw-bold">Upload Setup CSV</label><div class="input-group input-group-sm"><input type="file" name="csv_file" class="form-control" accept=".csv" required><button class="btn btn-success" type="submit"><i class="fa-solid fa-upload me-2"></i>Import CSV</button></div><div class="small text-secondary mt-1"><i class="fa-solid fa-circle-info me-1"></i>Importing a CSV will overwrite all current round configurations.</div></form></div></div></div>
        @endif
        @if ($tournament->teams->isEmpty())<div class="cricket-surface p-5 text-center"><span class="cricket-brand-mark mb-4"><i class="fa-solid fa-users"></i></span><h3 class="h4 fw-bold">Add teams before building picks</h3><p class="text-secondary mb-4">A pick cannot be assigned until the tournament has at least one team.</p><a href="{{ route('admin.tournaments.teams.index', $tournament) }}" class="btn btn-success">Manage teams <i class="fa-solid fa-arrow-right ms-2"></i></a></div>@else
            @if ($isLocked)
                <div class="cricket-surface p-4 p-lg-5"><div class="d-flex align-items-start justify-content-between gap-3 mb-4"><div><p class="cricket-kicker mb-1">Read-only sequence</p><h2 class="h3 fw-bold mb-1">Configured rounds and picks</h2><p class="text-secondary mb-0">Configuration changes are disabled after the draft starts.</p></div><span class="badge text-bg-warning">Locked</span></div>@foreach($draft->rounds as $round)<div class="cricket-surface-soft p-3 p-lg-4 mb-3"><div class="d-flex align-items-center justify-content-between mb-3"><div><div class="cricket-kicker">Round {{ $round->round_number }}</div><h3 class="h5 fw-bold mb-0">{{ $round->name ?: 'Round '.$round->round_number }}</h3></div><span class="badge text-bg-light">{{ ucfirst($round->status) }}</span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Pick</th><th>Team</th><th>Timer</th><th>Status</th><th>Player</th></tr></thead><tbody>@foreach($round->picks->sortBy('pick_number') as $pick)<tr><td class="fw-bold">#{{ $pick->pick_number }}</td><td>{{ $pick->team?->name ?: 'Unassigned' }}</td><td>{{ $pick->pick_duration }} sec</td><td><span class="badge text-bg-light">{{ ucfirst($pick->status) }}</span></td><td>{{ $pick->tournamentPlayer?->playerProfile?->full_name ?: '—' }}</td></tr>@endforeach</tbody></table></div></div>@endforeach<a href="{{ route('admin.tournaments.draft.control', $tournament) }}" class="btn btn-success"><i class="fa-solid fa-tower-broadcast me-2"></i>Open live control room</a></div>
            @else
            <form method="POST" action="{{ route('admin.tournaments.draft.setup.update', $tournament) }}">@csrf @method('PUT')
                <div class="d-flex flex-column flex-md-row align-items-md-end justify-content-between gap-3 mb-4"><div><p class="cricket-kicker mb-1">Draft rounds</p><h2 class="h3 fw-bold mb-1">The board sequence</h2><p class="text-secondary mb-0">Each row below becomes one draft pick slot.</p></div><button type="button" class="btn btn-success" @click="addRound()"><i class="fa-solid fa-plus me-2"></i>Add round</button></div>
                <template x-for="(round, roundIndex) in rounds" :key="round.key"><div class="cricket-surface p-4 p-lg-5 mb-4"><div class="d-flex flex-column flex-md-row align-items-md-end gap-3 mb-4"><div class="flex-grow-1"><p class="cricket-kicker mb-1" x-text="`Round ${round.round_number}`"></p><h3 class="h4 fw-bold mb-0">Round details</h3></div><button type="button" class="btn btn-sm btn-light text-danger" @click="removeRound(roundIndex)" :disabled="rounds.length === 1"><i class="fa-solid fa-trash me-2"></i>Remove round</button></div><div class="row g-3 mb-4"><div class="col-md-3"><label class="form-label">Round number</label><input type="number" min="1" class="form-control" :name="`rounds[${roundIndex}][round_number]`" x-model.number="round.round_number" required></div><div class="col-md-9"><label class="form-label">Round name <span class="text-secondary fw-normal">Optional</span></label><input type="text" maxlength="100" class="form-control" :name="`rounds[${roundIndex}][name]`" x-model="round.name" placeholder="Opening round"></div></div><div class="d-flex align-items-center justify-content-between gap-3 mb-2"><div><h4 class="h6 fw-bold mb-1">Pick slots</h4><p class="small text-secondary mb-0">Assign the team and timer for each exact pick number.</p></div><button type="button" class="btn btn-sm btn-outline-success" @click="addPick(roundIndex)"><i class="fa-solid fa-plus me-2"></i>Add pick</button></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pick number</th><th>Assigned team</th><th>Timer</th><th></th></tr></thead><tbody><template x-for="(pick, pickIndex) in round.picks" :key="pick.key"><tr><td><div class="input-group"><span class="input-group-text bg-light">#</span><input type="number" min="1" class="form-control" :name="`rounds[${roundIndex}][picks][${pickIndex}][pick_number]`" x-model.number="pick.pick_number" required></div></td><td><select class="form-select" :name="`rounds[${roundIndex}][picks][${pickIndex}][team_id]`" x-model="pick.team_id" required><option value="">Select team</option>@foreach ($tournament->teams as $team)<option value="{{ $team->id }}">{{ $team->name }}</option>@endforeach</select></td><td><div class="input-group"><input type="number" min="5" max="3600" class="form-control" :name="`rounds[${roundIndex}][picks][${pickIndex}][pick_duration]`" x-model.number="pick.pick_duration" required><span class="input-group-text bg-light">sec</span></div></td><td class="text-end"><button type="button" class="btn btn-sm btn-light text-danger" @click="removePick(roundIndex, pickIndex)" :disabled="round.picks.length === 1" aria-label="Remove pick"><i class="fa-solid fa-trash"></i></button></td></tr></template></tbody></table></div></div></template>
                <div class="d-flex flex-wrap justify-content-end gap-2"><a href="{{ route('admin.tournaments.show', $tournament) }}" class="btn btn-light">Cancel</a><button type="submit" class="btn btn-success btn-lg"><i class="fa-solid fa-floppy-disk me-2"></i>Save draft setup</button></div>
            </form>
            @endif
        @endif
    </div>
    <script>
        function draftSetupForm() { const existing = @js($draft->rounds->map(fn ($round) => ['key' => 'round-'.$round->id, 'round_number' => $round->round_number, 'name' => $round->name, 'picks' => $round->picks->map(fn ($pick) => ['key' => 'pick-'.$pick->id, 'pick_number' => $pick->pick_number, 'team_id' => (string) $pick->team_id, 'pick_duration' => $pick->pick_duration])->values()])->values()); return { nextKey: 1, rounds: existing.length ? existing : [{ key: 'round-new-0', round_number: 1, name: 'Round 1', picks: [{ key: 'pick-new-0', pick_number: 1, team_id: '', pick_duration: {{ $tournament->default_pick_duration }} }] }], addRound() { const number = this.rounds.length + 1; this.rounds.push({ key: `round-new-${this.nextKey++}`, round_number: number, name: `Round ${number}`, picks: [{ key: `pick-new-${this.nextKey++}`, pick_number: this.nextPickNumber(), team_id: '', pick_duration: {{ $tournament->default_pick_duration }} }] }); }, removeRound(index) { if (this.rounds.length > 1) this.rounds.splice(index, 1); }, addPick(roundIndex) { this.rounds[roundIndex].picks.push({ key: `pick-new-${this.nextKey++}`, pick_number: this.nextPickNumber(), team_id: '', pick_duration: {{ $tournament->default_pick_duration }} }); }, removePick(roundIndex, pickIndex) { if (this.rounds[roundIndex].picks.length > 1) this.rounds[roundIndex].picks.splice(pickIndex, 1); }, nextPickNumber() { return this.rounds.reduce((max, round) => Math.max(max, ...round.picks.map(pick => Number(pick.pick_number) || 0)), 0) + 1; } }; }
    </script>
</x-app-layout>
